-- Navigate to `~/.local/share/nvim/lazy/avante.nvim` and then compile it from source: `make BUILD_FROM_SOURCE=true`
return {
    -- "yetone/avante.nvim",
    -- -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
    -- -- ⚠️ must add this setting! ! !
    -- build = vim.fn.has("win32") ~= 0
    --     and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
    --     or "make",
    -- event = "VeryLazy",
    -- version = false, -- Never set this value to "*"! Never!
    -- init = function()
    --     -- Function to clean the package.path and package.cpath
    --     local function clean_path(current_path)
    --         local paths = {}
    --         for path in string.gmatch(current_path, "[^;]+") do
    --             -- Remove the path that causes the "Is a directory" error
    --             if not path:find("/usr/local/share/lua/5.1", 1, true) then
    --                 table.insert(paths, path)
    --             end
    --         end
    --         return table.concat(paths, ";")
    --     end
    --
    --     -- 3. Apply cleanup and give priority to Avante
    --     -- package.cpath = build_path .. ";" .. clean_path(package.cpath)
    --     package.path = clean_path(package.path)
    -- end,
    -- ---@module 'avante'
    -- ---@type avante.Config
    -- opts = {
    --     -- add any opts here
    --     -- this file can contain specific instructions for your project
    --     instructions_file = "avante.md",
    --     -- for example
    --     -- provider = "claude",
    --     -- providers = {
    --     --     claude = {
    --     --         endpoint = "https://api.anthropic.com",
    --     --         model = "claude-sonnet-4-20250514",
    --     --         timeout = 30000, -- Timeout in milliseconds
    --     --         extra_request_body = {
    --     --             temperature = 0.75,
    --     --             max_tokens = 20480,
    --     --         },
    --     --     },
    --     --     moonshot = {
    --     --         endpoint = "https://api.moonshot.ai/v1",
    --     --         model = "kimi-k2-0711-preview",
    --     --         timeout = 30000, -- Timeout in milliseconds
    --     --         extra_request_body = {
    --     --             temperature = 0.75,
    --     --             max_tokens = 32768,
    --     --         },
    --     --     },
    --     -- },
    --     -- provider = "gemini-cli",
    --     provider = "copilot",
    --     acp_providers = {
    --         ["gemini-cli"] = {
    --             command = "gemini",
    --             args = { "--experimental-acp" },
    --             env = {
    --                 NODE_NO_WARNINGS = "1",
    --                 GEMINI_API_KEY = os.getenv("GEMINI_API_KEY"),
    --             },
    --         }
    --     },
    --     selector = {
    --         provider = "telescope",   -- "native"
    --         provider_opts = {},
    --         exclude_auto_select = {}, -- List of items to exclude from auto selection
    --     },
    -- },
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "MunifTanjim/nui.nvim",
    --     --- The below dependencies are optional,
    --     "nvim-tree/nvim-web-devicons",
    --     {
    --         -- support for image pasting
    --         "HakonHarnes/img-clip.nvim",
    --         event = "VeryLazy",
    --         opts = {
    --             -- recommended settings
    --             default = {
    --                 embed_image_as_base64 = false,
    --                 prompt_for_file_name = false,
    --                 drag_and_drop = {
    --                     insert_mode = true,
    --                 },
    --                 -- required for Windows users
    --                 use_absolute_path = true,
    --             },
    --         },
    --     },
    --     {
    --         -- Make sure to set this up properly if you have lazy=true
    --         'MeanderingProgrammer/render-markdown.nvim',
    --         opts = {
    --             file_types = { "markdown", "Avante" },
    --         },
    --         ft = { "markdown", "Avante" },
    --     },
    -- },
    -- -- config = function()
    -- --     require('avante_lib').load()
    -- --     local config = {
    -- --         windows = {
    -- --             input = {
    -- --                 border = "rounded",
    -- --                 width = 60,
    -- --                 height = 10,
    -- --             },
    -- --             output = {
    -- --                 border = "rounded",
    -- --                 width = 60,
    -- --                 height = 20,
    -- --             },
    -- --             ask = {
    -- --                 floating = true,
    -- --                 border = "rounded",
    -- --                 start_insert = true
    -- --             }
    -- --         }
    -- --     }
    -- --     local avante = require('avante')
    -- --     avante.setup(config)
    -- --
    -- --     vim.keymap.set({ 'v', 'n' }, '<D-S-b>', function()
    -- --         require('avante').toggle()
    -- --     end, { desc = "Avante: Toggle Assistant" })
    -- --
    -- -- vim.keymap.set({ 'v', 'n' }, '<C-Enter>', "<Cmd>:AvanteEdit<CR>", { desc = "Avante: Edit with Assistant" })
    -- -- end
}
